version: "3"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=fastapi
      - SECRET_KEY=3608e036df0efd756f0a1346d108db166712d9a47e4f1dc486905b806a787d65
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
